// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDTfu3_3kz_MmlxI8B96DICWFLNtHOkEc',
    appId: '1:677832762023:web:90080669ec76c4443ef182',
    messagingSenderId: '677832762023',
    projectId: 'carrentapp-4321f',
    authDomain: 'carrentapp-4321f.firebaseapp.com',
    storageBucket: 'carrentapp-4321f.appspot.com',
    measurementId: 'G-JSQSYK3QYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1OlkZcSzNaStsCY9Cl2-1Yuem5QfUicU',
    appId: '1:677832762023:android:f2ebade5e1107f9e3ef182',
    messagingSenderId: '677832762023',
    projectId: 'carrentapp-4321f',
    storageBucket: 'carrentapp-4321f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMpY93Mzgvocp5fPMReIgZh6BJ4QJaFlI',
    appId: '1:677832762023:ios:e3278df88bca3f253ef182',
    messagingSenderId: '677832762023',
    projectId: 'carrentapp-4321f',
    storageBucket: 'carrentapp-4321f.appspot.com',
    iosBundleId: 'com.example.carRentMapFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMpY93Mzgvocp5fPMReIgZh6BJ4QJaFlI',
    appId: '1:677832762023:ios:e3278df88bca3f253ef182',
    messagingSenderId: '677832762023',
    projectId: 'carrentapp-4321f',
    storageBucket: 'carrentapp-4321f.appspot.com',
    iosBundleId: 'com.example.carRentMapFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDTfu3_3kz_MmlxI8B96DICWFLNtHOkEc',
    appId: '1:677832762023:web:90c98cf816858b663ef182',
    messagingSenderId: '677832762023',
    projectId: 'carrentapp-4321f',
    authDomain: 'carrentapp-4321f.firebaseapp.com',
    storageBucket: 'carrentapp-4321f.appspot.com',
    measurementId: 'G-CXJH005FHB',
  );
}
